/* eslint-disable react/no-unknown-property */
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import request from '../lib/request';
import LandingPage from '../components/LandingPage/LandingPage';
import { useEffect } from 'react';

export default function Home({settings}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Buy VPN With Paypal | Red Card VPN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <LandingPage settings={settings[0]} />
    </div>
  )
}

export async function getServerSideProps({context}){
  const homeSettings = await request('home/view');

  if (!homeSettings?.data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      settings: homeSettings?.data,
      // fallback: false,
    }
  }
}